#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from sql.ypp  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	IDENT	258
#define	NUMBER	259
#define	STRING	260
#define	NUL	261
#define	SELECT	262
#define	AS	263
#define	FROM	264
#define	WHERE	265
#define	GROUP	266
#define	BY	267
#define	HAVING	268
#define	ORDER	269
#define	ASC	270
#define	DESC	271
#define	INSERT	272
#define	INTO	273
#define	VALUES	274
#define	UPDATE	275
#define	SET	276
#define	DELETE	277
#define	CREATE	278
#define	TABLE	279
#define	DESCRIBE	280
#define	SHOW	281
#define	TABLES	282
#define	DROP	283
#define	PRIMARY	284
#define	DISTINCT	285
#define	KEY	286
#define	NOTEQ	287
#define	GEQ	288
#define	LEQ	289
#define	AND	290
#define	OR	291
#define	NOT	292
#define	QUIT	293


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int IDENT;
static const int NUMBER;
static const int STRING;
static const int NUL;
static const int SELECT;
static const int AS;
static const int FROM;
static const int WHERE;
static const int GROUP;
static const int BY;
static const int HAVING;
static const int ORDER;
static const int ASC;
static const int DESC;
static const int INSERT;
static const int INTO;
static const int VALUES;
static const int UPDATE;
static const int SET;
static const int DELETE;
static const int CREATE;
static const int TABLE;
static const int DESCRIBE;
static const int SHOW;
static const int TABLES;
static const int DROP;
static const int PRIMARY;
static const int DISTINCT;
static const int KEY;
static const int NOTEQ;
static const int GEQ;
static const int LEQ;
static const int AND;
static const int OR;
static const int NOT;
static const int QUIT;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,IDENT=258
	,NUMBER=259
	,STRING=260
	,NUL=261
	,SELECT=262
	,AS=263
	,FROM=264
	,WHERE=265
	,GROUP=266
	,BY=267
	,HAVING=268
	,ORDER=269
	,ASC=270
	,DESC=271
	,INSERT=272
	,INTO=273
	,VALUES=274
	,UPDATE=275
	,SET=276
	,DELETE=277
	,CREATE=278
	,TABLE=279
	,DESCRIBE=280
	,SHOW=281
	,TABLES=282
	,DROP=283
	,PRIMARY=284
	,DISTINCT=285
	,KEY=286
	,NOTEQ=287
	,GEQ=288
	,LEQ=289
	,AND=290
	,OR=291
	,NOT=292
	,QUIT=293


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::IDENT=258;
const int YY_parse_CLASS::NUMBER=259;
const int YY_parse_CLASS::STRING=260;
const int YY_parse_CLASS::NUL=261;
const int YY_parse_CLASS::SELECT=262;
const int YY_parse_CLASS::AS=263;
const int YY_parse_CLASS::FROM=264;
const int YY_parse_CLASS::WHERE=265;
const int YY_parse_CLASS::GROUP=266;
const int YY_parse_CLASS::BY=267;
const int YY_parse_CLASS::HAVING=268;
const int YY_parse_CLASS::ORDER=269;
const int YY_parse_CLASS::ASC=270;
const int YY_parse_CLASS::DESC=271;
const int YY_parse_CLASS::INSERT=272;
const int YY_parse_CLASS::INTO=273;
const int YY_parse_CLASS::VALUES=274;
const int YY_parse_CLASS::UPDATE=275;
const int YY_parse_CLASS::SET=276;
const int YY_parse_CLASS::DELETE=277;
const int YY_parse_CLASS::CREATE=278;
const int YY_parse_CLASS::TABLE=279;
const int YY_parse_CLASS::DESCRIBE=280;
const int YY_parse_CLASS::SHOW=281;
const int YY_parse_CLASS::TABLES=282;
const int YY_parse_CLASS::DROP=283;
const int YY_parse_CLASS::PRIMARY=284;
const int YY_parse_CLASS::DISTINCT=285;
const int YY_parse_CLASS::KEY=286;
const int YY_parse_CLASS::NOTEQ=287;
const int YY_parse_CLASS::GEQ=288;
const int YY_parse_CLASS::LEQ=289;
const int YY_parse_CLASS::AND=290;
const int YY_parse_CLASS::OR=291;
const int YY_parse_CLASS::NOT=292;
const int YY_parse_CLASS::QUIT=293;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		149
#define	YYFLAG		-32768
#define	YYNTBASE	50

#define YYTRANSLATE(x) ((unsigned)(x) <= 293 ? yytranslate[x] : 74)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,    40,
    41,    48,    46,    43,    47,     2,    49,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    39,    45,
    42,    44,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     1,     4,     8,    17,    23,    26,    36,    43,    51,
    55,    59,    64,    67,    69,    71,    73,    77,    83,    89,
    93,    97,    99,   104,   108,   110,   114,   116,   118,   120,
   129,   130,   133,   134,   137,   138,   142,   144,   148,   150,
   151,   155,   157,   161,   163,   166,   169,   171,   174,   177,
   179,   180,   183,   187,   191,   193,   195,   199,   201,   203,
   205,   209,   213,   217,   219,   223,   225,   228,   232,   234,
   236,   238,   240,   242,   244,   246,   248,   250,   252,   254
};

static const short yyrhs[] = {    -1,
    50,    51,     0,    50,    38,    39,     0,    17,    18,    52,
    19,    40,    70,    41,    39,     0,    17,    18,    52,    58,
    39,     0,    58,    39,     0,    20,    52,    21,    53,    42,
    54,    10,    54,    39,     0,    22,     9,    52,    10,    54,
    39,     0,    23,    24,    52,    40,    71,    41,    39,     0,
    25,    52,    39,     0,    26,    27,    39,     0,    28,    24,
    52,    39,     0,     1,    39,     0,     3,     0,     3,     0,
    57,     0,    54,    73,    57,     0,    54,    73,    40,    54,
    41,     0,    54,    73,    40,    58,    41,     0,    40,    58,
    41,     0,    40,    54,    41,     0,    55,     0,     3,    40,
    56,    41,     0,     3,    40,    41,     0,    54,     0,    56,
    43,    54,     0,     3,     0,     4,     0,     5,     0,     7,
    67,     9,    69,    59,    61,    60,    64,     0,     0,    10,
    54,     0,     0,    13,    54,     0,     0,    11,    12,    62,
     0,    63,     0,    62,    43,    63,     0,    53,     0,     0,
    14,    12,    65,     0,    66,     0,    65,    43,    66,     0,
     4,     0,     4,    15,     0,     4,    16,     0,    53,     0,
    53,    15,     0,    53,    16,     0,    68,     0,     0,    30,
    68,     0,    67,    43,    68,     0,    54,     8,    53,     0,
    53,     0,    52,     0,    69,    43,    52,     0,     4,     0,
     5,     0,     6,     0,    70,    43,     4,     0,    70,    43,
     5,     0,    70,    43,     6,     0,    72,     0,    71,    43,
    72,     0,    53,     0,    53,    31,     0,    53,    29,    31,
     0,    42,     0,    32,     0,    44,     0,    45,     0,    33,
     0,    34,     0,    46,     0,    47,     0,    48,     0,    49,
     0,    35,     0,    36,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    42,    43,    44,    47,    50,    53,    56,    59,    62,    65,
    69,    73,    76,    81,    87,    93,    94,    96,    98,   100,
   102,   104,   108,   110,   114,   116,   121,   123,   125,   129,
   139,   140,   143,   144,   147,   148,   152,   154,   158,   161,
   162,   166,   168,   172,   174,   176,   178,   180,   182,   186,
   188,   188,   189,   193,   195,   199,   201,   205,   207,   209,
   211,   213,   215,   220,   222,   226,   228,   230,   234,   235,
   236,   237,   238,   239,   240,   241,   242,   243,   244,   245
};

static const char * const yytname[] = {   "$","error","$illegal.","IDENT","NUMBER",
"STRING","NUL","SELECT","AS","FROM","WHERE","GROUP","BY","HAVING","ORDER","ASC",
"DESC","INSERT","INTO","VALUES","UPDATE","SET","DELETE","CREATE","TABLE","DESCRIBE",
"SHOW","TABLES","DROP","PRIMARY","DISTINCT","KEY","NOTEQ","GEQ","LEQ","AND",
"OR","NOT","QUIT","';'","'('","')'","'='","','","'>'","'<'","'+'","'-'","'*'",
"'/'","program","sql_command","tablename","colname","expr","fcall","fncargs",
"value","select_expr","whereclause","havingclause","groupclause","grouplist",
"groupspec","orderclause","orderlist","orderspec","projection","outcol","join",
"data_list","column_decls","column_decl","bin_op",""
};
#endif

static const short yyr1[] = {     0,
    50,    50,    50,    51,    51,    51,    51,    51,    51,    51,
    51,    51,    51,    52,    53,    54,    54,    54,    54,    54,
    54,    54,    55,    55,    56,    56,    57,    57,    57,    58,
    59,    59,    60,    60,    61,    61,    62,    62,    63,    64,
    64,    65,    65,    66,    66,    66,    66,    66,    66,    67,
    67,    67,    67,    68,    68,    69,    69,    70,    70,    70,
    70,    70,    70,    71,    71,    72,    72,    72,    73,    73,
    73,    73,    73,    73,    73,    73,    73,    73,    73,    73
};

static const short yyr2[] = {     0,
     0,     2,     3,     8,     5,     2,     9,     6,     7,     3,
     3,     4,     2,     1,     1,     1,     3,     5,     5,     3,
     3,     1,     4,     3,     1,     3,     1,     1,     1,     8,
     0,     2,     0,     2,     0,     3,     1,     3,     1,     0,
     3,     1,     3,     1,     2,     2,     1,     2,     2,     1,
     0,     2,     3,     3,     1,     1,     3,     1,     1,     1,
     3,     3,     3,     1,     3,     1,     2,     3,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     1
};

static const short yydefact[] = {     1,
     0,     0,    51,     0,     0,     0,     0,     0,     0,     0,
     0,     2,     0,    13,    27,    28,    29,     0,     0,    55,
     0,    22,    16,     0,    50,     0,    14,     0,     0,     0,
     0,     0,     0,     3,     6,     0,    52,    27,     0,     0,
     0,    70,    73,    74,    79,    80,    69,    71,    72,    75,
    76,    77,    78,     0,     0,     0,     0,     0,     0,     0,
    10,    11,     0,    24,    25,     0,    21,    20,    15,    54,
    27,     0,    17,    56,    31,    53,     0,     0,     0,     0,
     0,    12,    23,     0,     0,     0,     0,     0,    35,     0,
     5,     0,     0,    66,     0,    64,    26,    18,    19,    32,
    57,     0,    33,    58,    59,    60,     0,     0,     8,     0,
    67,     0,     0,     0,     0,    40,     0,     0,     0,    68,
     9,    65,    39,    36,    37,    34,     0,    30,     4,    61,
    62,    63,     0,     0,     0,     7,    38,    44,    47,    41,
    42,    45,    46,    48,    49,     0,    43,     0,     0
};

static const short yydefgoto[] = {     1,
    12,    28,    20,    21,    22,    66,    23,    13,    89,   116,
   103,   124,   125,   128,   140,   141,    24,    25,    75,   107,
    95,    96,    54
};

static const short yypact[] = {-32768,
     8,   -27,    56,    -2,    19,    20,    44,    19,     5,    59,
     6,-32768,    75,-32768,    -5,-32768,-32768,    99,    60,-32768,
    43,-32768,-32768,     4,-32768,    19,-32768,    77,    19,    19,
    76,    78,    19,-32768,-32768,     2,-32768,    87,    96,    58,
    92,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,   108,    19,    99,     7,    92,   126,   106,
-32768,-32768,   110,-32768,   172,   -22,-32768,-32768,-32768,-32768,
-32768,    60,-32768,-32768,     1,-32768,   107,   119,   131,   121,
    92,-32768,-32768,   121,   118,   133,   121,    19,   165,   129,
-32768,   121,   136,    21,    -4,-32768,   172,-32768,-32768,   172,
-32768,   167,   164,-32768,-32768,-32768,    12,    74,-32768,   160,
-32768,   153,    92,    92,   121,   180,   156,   151,   121,-32768,
-32768,-32768,-32768,   166,-32768,   172,   185,-32768,-32768,-32768,
-32768,-32768,   154,    92,    54,-32768,-32768,    55,    65,   168,
-32768,-32768,-32768,-32768,-32768,    54,-32768,   210,-32768
};

static const short yypgoto[] = {-32768,
-32768,    -6,   -41,   -18,-32768,-32768,   158,   -16,-32768,-32768,
-32768,-32768,    79,-32768,-32768,    69,-32768,    -8,-32768,-32768,
-32768,   109,-32768
};


#define	YYLAST		222


static const short yytable[] = {    70,
    39,    31,    40,   -15,    38,    16,    17,   148,     2,    37,
    87,    14,    55,     3,     3,    26,    79,    65,    83,    57,
    84,    27,    59,    60,     4,    77,    63,     5,    29,     6,
     7,    32,     8,     9,    36,    10,   112,   -15,   113,    94,
    78,    19,    64,    88,    34,    11,    56,    76,    74,   110,
    41,   111,   117,    85,   118,    86,    69,   138,    15,    16,
    17,    93,    38,    16,    17,    97,     3,    30,   100,   142,
   143,    94,   123,   108,    42,    43,    44,    45,    46,   144,
   145,   101,    33,   119,    47,    18,    48,    49,    50,    51,
    52,    53,   123,   139,    69,    19,   126,    58,    68,    19,
   133,    15,    16,    17,   139,    42,    43,    44,    45,    46,
    71,    16,    17,    35,    61,    47,    62,    48,    49,    50,
    51,    52,    53,    38,    16,    17,    36,    42,    43,    44,
    45,    46,   104,   105,   106,    80,    67,    47,    19,    48,
    49,    50,    51,    52,    53,    81,    90,    72,    82,    42,
    43,    44,    45,    46,   130,   131,   132,    91,    98,    47,
    19,    48,    49,    50,    51,    52,    53,    42,    43,    44,
    45,    46,    92,    99,   109,   102,   115,    47,   114,    48,
    49,    50,    51,    52,    53,    42,    43,    44,    45,    46,
   120,   121,   136,   127,   129,    47,   135,    48,    49,    50,
    51,    52,    53,    42,    43,    44,    45,    46,   134,   149,
   146,    73,   137,    47,   147,    48,    49,    50,    51,    52,
    53,   122
};

static const short yycheck[] = {    41,
    19,     8,    19,     9,     3,     4,     5,     0,     1,    18,
    10,    39,     9,     7,     7,    18,    58,    36,    41,    26,
    43,     3,    29,    30,    17,    19,    33,    20,     9,    22,
    23,    27,    25,    26,    40,    28,    41,    43,    43,    81,
    57,    40,    41,    43,    39,    38,    43,    56,    55,    29,
     8,    31,    41,    72,    43,    72,     3,     4,     3,     4,
     5,    80,     3,     4,     5,    84,     7,    24,    87,    15,
    16,   113,   114,    92,    32,    33,    34,    35,    36,    15,
    16,    88,    24,    10,    42,    30,    44,    45,    46,    47,
    48,    49,   134,   135,     3,    40,   115,    21,    41,    40,
   119,     3,     4,     5,   146,    32,    33,    34,    35,    36,
     3,     4,     5,    39,    39,    42,    39,    44,    45,    46,
    47,    48,    49,     3,     4,     5,    40,    32,    33,    34,
    35,    36,     4,     5,     6,    10,    41,    42,    40,    44,
    45,    46,    47,    48,    49,    40,    40,    40,    39,    32,
    33,    34,    35,    36,     4,     5,     6,    39,    41,    42,
    40,    44,    45,    46,    47,    48,    49,    32,    33,    34,
    35,    36,    42,    41,    39,    11,    13,    42,    12,    44,
    45,    46,    47,    48,    49,    32,    33,    34,    35,    36,
    31,    39,    39,    14,    39,    42,    12,    44,    45,    46,
    47,    48,    49,    32,    33,    34,    35,    36,    43,     0,
    43,    54,   134,    42,   146,    44,    45,    46,    47,    48,
    49,   113
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 3:
#line 44 "sql.ypp"
{ YYACCEPT; ;
    break;}
case 4:
#line 48 "sql.ypp"
{ evalexpr(optimize(compile(cvt_itoe(makeexpr(OP_INSERTROW, 2, yyvsp[-5], yyvsp[-2]))))); yyval=0; freen=0; ;
    break;}
case 5:
#line 51 "sql.ypp"
{ printf("Multi-row insert not implemented yet\n"); freen=0; ;
    break;}
case 6:
#line 54 "sql.ypp"
{ print_relation(evalexpr(optimize(compile(cvt_itoe(yyvsp[-1]))))); freen=0; ;
    break;}
case 7:
#line 57 "sql.ypp"
{  evalexpr(optimize(compile(cvt_itoe( update_table( yyvsp[-7], makeexpr(OP_SET, 2, yyvsp[-5], yyvsp[-3]), yyvsp[-1]  ) )))); ;
    break;}
case 8:
#line 60 "sql.ypp"
{ evalexpr(optimize(compile(cvt_itoe(makeexpr(OP_DELETE, 2, yyvsp[-3], yyvsp[-1]))))); ;
    break;}
case 9:
#line 63 "sql.ypp"
{ evalexpr(optimize(compile(cvt_itoe(makeexpr(OP_CREATETABLE, 2, yyvsp[-4], yyvsp[-2]))))); yyval=0; freen=0; ;
    break;}
case 10:
#line 66 "sql.ypp"
{ printf("DESCRIBE not implemented yet\n"); freen=0; ;
    break;}
case 11:
#line 70 "sql.ypp"
{ printf("SHOW TABLES not implemented yet\n"); freen=0; ;
    break;}
case 12:
#line 74 "sql.ypp"
{ evalexpr(optimize(compile(cvt_itoe(drop_table(cvt_itoe(yyvsp[-1])))))); ;
    break;}
case 13:
#line 77 "sql.ypp"
{ freen = 0; ;
    break;}
case 14:
#line 82 "sql.ypp"
{
		  yyval = setname(OP_TABLENAME, yyvsp[0]);
		;
    break;}
case 15:
#line 88 "sql.ypp"
{
		  yyval = setname(OP_COLNAME, yyvsp[0]);
		;
    break;}
case 17:
#line 95 "sql.ypp"
{ yyval = makeexpr(yyvsp[-1], 2, yyvsp[-2], yyvsp[0]); ;
    break;}
case 18:
#line 97 "sql.ypp"
{ yyval = makeexpr(yyvsp[-3], 2, yyvsp[-4], yyvsp[-1]); ;
    break;}
case 19:
#line 99 "sql.ypp"
{ yyval = makeexpr(yyvsp[-3], 2, yyvsp[-4], yyvsp[-1]); ;
    break;}
case 20:
#line 101 "sql.ypp"
{ yyval = yyvsp[-1]; ;
    break;}
case 21:
#line 103 "sql.ypp"
{ yyval = yyvsp[-1]; ;
    break;}
case 22:
#line 105 "sql.ypp"
{ yyval = yyvsp[0]; ;
    break;}
case 23:
#line 109 "sql.ypp"
{ yyval = makeexpr(OP_FCALL, 2, setname(OP_FNAME, yyvsp[-3]), yyvsp[-1]); ;
    break;}
case 24:
#line 111 "sql.ypp"
{ yyval = makeexpr(OP_FCALL, 2, setname(OP_FNAME, yyvsp[-2]), 0); ;
    break;}
case 25:
#line 115 "sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, yyvsp[0], 0); ;
    break;}
case 26:
#line 117 "sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, yyvsp[0], yyvsp[-2]); ;
    break;}
case 27:
#line 122 "sql.ypp"
{ yyval = setname(OP_COLNAME, yyvsp[0]); ;
    break;}
case 28:
#line 124 "sql.ypp"
{ yyval = yyvsp[0]; ;
    break;}
case 29:
#line 126 "sql.ypp"
{ yyval = yyvsp[0]; ;
    break;}
case 30:
#line 130 "sql.ypp"
{ yyval = yyvsp[-4];
		  if(yyvsp[-3]) yyval = makeexpr(OP_SELECTION, 2, yyval, yyvsp[-3]);
		  if(yyvsp[-2]) yyval = makeexpr(OP_GROUP, 2, yyval, yyvsp[-2]);
		  yyval = makeexpr(OP_PROJECTION, 2, yyval, yyvsp[-6]);
		  if(yyvsp[-1]) yyval = makeexpr(OP_SELECTION, 2, yyval, yyvsp[-1]);
		  if(yyvsp[0]) yyval = makeexpr(OP_SORT, 2, yyval, yyvsp[0]);
		;
    break;}
case 31:
#line 139 "sql.ypp"
{ yyval = 0; ;
    break;}
case 32:
#line 140 "sql.ypp"
{ yyval = yyvsp[0]; ;
    break;}
case 33:
#line 143 "sql.ypp"
{ yyval = 0; ;
    break;}
case 34:
#line 144 "sql.ypp"
{ yyval = yyvsp[0]; ;
    break;}
case 35:
#line 147 "sql.ypp"
{ yyval = 0; ;
    break;}
case 36:
#line 149 "sql.ypp"
{ yyval = yyvsp[0]; ;
    break;}
case 37:
#line 153 "sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, yyvsp[0], 0); ;
    break;}
case 38:
#line 155 "sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, yyvsp[0], yyvsp[-2]); ;
    break;}
case 40:
#line 161 "sql.ypp"
{ yyval = 0; ;
    break;}
case 41:
#line 163 "sql.ypp"
{ yyval = yyvsp[0]; ;
    break;}
case 42:
#line 167 "sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, yyvsp[0], 0); ;
    break;}
case 43:
#line 169 "sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, yyvsp[0], yyvsp[-2]); ;
    break;}
case 44:
#line 173 "sql.ypp"
{ yyval = makeexpr(OP_SORTSPEC, 2, yyvsp[0], 0); ;
    break;}
case 45:
#line 175 "sql.ypp"
{ yyval = makeexpr(OP_SORTSPEC, 2, yyvsp[-1], 0); ;
    break;}
case 46:
#line 177 "sql.ypp"
{ yyval = makeexpr(OP_SORTSPEC, 2, yyvsp[-1], makeexpr(OP_NULL, 0, 0, 0)); ;
    break;}
case 47:
#line 179 "sql.ypp"
{ yyval = makeexpr(OP_SORTSPEC, 2, setname(OP_COLNAME, yyvsp[0]), 0); ;
    break;}
case 48:
#line 181 "sql.ypp"
{ yyval = makeexpr(OP_SORTSPEC, 2, setname(OP_COLNAME, yyvsp[-1]), 0); ;
    break;}
case 49:
#line 183 "sql.ypp"
{ yyval = makeexpr(OP_SORTSPEC, 2, setname(OP_COLNAME, yyvsp[-1]), makeexpr(OP_NULL, 0, 0, 0)); ;
    break;}
case 50:
#line 187 "sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, yyvsp[0], 0); ;
    break;}
case 52:
#line 188 "sql.ypp"
{ yyval = makeexpr(OP_DISTINCT, 1, makeexpr(OP_RLIST, 2, yyvsp[0], 0), 0); ;
    break;}
case 53:
#line 190 "sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, yyvsp[0], yyvsp[-2]); ;
    break;}
case 54:
#line 194 "sql.ypp"
{ yyval = makeexpr(OP_OUTCOLNAME, 2, yyvsp[-2], yyvsp[0]); ;
    break;}
case 55:
#line 196 "sql.ypp"
{ yyval = makeexpr(OP_OUTCOLNAME, 2, yyvsp[0], yyvsp[0]); ;
    break;}
case 56:
#line 200 "sql.ypp"
{ yyval = yyvsp[0]; ;
    break;}
case 57:
#line 202 "sql.ypp"
{ yyval = makeexpr(OP_PRODUCT, 2, yyvsp[-2], yyvsp[0]); ;
    break;}
case 58:
#line 206 "sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, yyvsp[0], 0); ;
    break;}
case 59:
#line 208 "sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, yyvsp[0], 0); ;
    break;}
case 60:
#line 210 "sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, makeexpr(OP_NULL,0,0, 0), 0); ;
    break;}
case 61:
#line 212 "sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, yyvsp[0], yyvsp[-2]); ;
    break;}
case 62:
#line 214 "sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, yyvsp[0], yyvsp[-2]); ;
    break;}
case 63:
#line 216 "sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, makeexpr(OP_NULL, 0, 0, 0), yyvsp[-2]); ;
    break;}
case 64:
#line 221 "sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, yyvsp[0], 0); ;
    break;}
case 65:
#line 223 "sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, yyvsp[0], yyvsp[-2]); ;
    break;}
case 66:
#line 227 "sql.ypp"
{ yyval = makeexpr(OP_COLUMNDEF, 2, yyvsp[0], 0); ;
    break;}
case 67:
#line 229 "sql.ypp"
{ yyval = makeexpr(OP_COLUMNDEF, 2, yyvsp[-1], 1); ;
    break;}
case 68:
#line 231 "sql.ypp"
{ yyval = makeexpr(OP_COLUMNDEF, 2, yyvsp[-2], 3); ;
    break;}
case 69:
#line 234 "sql.ypp"
{ yyval = OP_EQUAL; ;
    break;}
case 70:
#line 235 "sql.ypp"
{ yyval = OP_NOTEQ; ;
    break;}
case 71:
#line 236 "sql.ypp"
{ yyval = OP_GT; ;
    break;}
case 72:
#line 237 "sql.ypp"
{ yyval = OP_LT; ;
    break;}
case 73:
#line 238 "sql.ypp"
{ yyval = OP_GEQ; ;
    break;}
case 74:
#line 239 "sql.ypp"
{ yyval = OP_LEQ; ;
    break;}
case 75:
#line 240 "sql.ypp"
{ yyval = OP_PLUS; ;
    break;}
case 76:
#line 241 "sql.ypp"
{ yyval = OP_BMINUS; ;
    break;}
case 77:
#line 242 "sql.ypp"
{ yyval = OP_TIMES; ;
    break;}
case 78:
#line 243 "sql.ypp"
{ yyval = OP_DIVIDE; ;
    break;}
case 79:
#line 244 "sql.ypp"
{ yyval = OP_AND; ;
    break;}
case 80:
#line 245 "sql.ypp"
{ yyval = OP_OR; ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 248 "sql.ypp"

int
yyerror(char const *str)
{
	printf("Line %d: %s\n", linenum, str);
	return 1;
}

